### ISSUE TITLE
ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by luciferlinx101** [punica-ai/punica#16]
Amazing work on Punica read the research paper @abcdabcd987
I am having some issue running `python examples/tui-multi-lora.py`

I am getting following error : 
(muti-tenant-test-2) ubuntu@ip-10-14-1-163:~/multi-tenant-test/punica$ python examples/tui-multi-lora.py
Traceback (most recent call last):
  File "/home/ubuntu/multi-tenant-test/punica/examples/tui-multi-lora.py", line 11, in <module>
    from rich.containers import Lines
ModuleNotFoundError: No module named 'rich'

**Comment by abcdabcd987** [comment]
Examples and benchmarks have more dependencies. They are listed in [`pyproject.toml`](https://github.com/punica-ai/punica/blob/master/pyproject.toml). You need to `pip install` them.

Alternatively, you can install them by `pip install -e .[dev]`.

**Comment by luciferlinx101** [comment]
Thanks!  `pip install -e .[dev]` worked
