### ISSUE TITLE
BGMV performs better than SGMV?

### ISSUE THREAD

**Issue by ghost** [punica-ai/punica#40]
I benchmarked various kernels on the A100 using the [benchmark script](https://github.com/punica-ai/punica/blob/master/benchmarks/bench_sgmv.py), and it seems that the BGMV kernel outperforms the SGMV kernels for individual requests (bgmv senario). Is this expected?

<img width="852" alt="Screenshot 2024-01-31 at 4 28 27 PM" src="https://github.com/punica-ai/punica/assets/84881952/cabe1c29-1dfc-4b9a-830f-471d94f9fd34">

**Comment by yzh119** [comment]
Hi @jsheng-jian , thanks for doing the benchmark and yes it's somewhat expected considering the current SGMV implementation is not optimized for individual requests. A better implementation of SGMV (we are integrating them into flashinfer) may have a similar performance to bgmv but I don't expect sgmv would be faster in this case.
