### ISSUE TITLE
Support Continuous Batching?

### ISSUE THREAD

**Issue by Wisley1998** [punica-ai/punica#45]
Hi. I've read Punica paper. It says that "We put the batching dimension on the outmost to enable continuous batching" in Sec 5.4. Could you please tell me which code of Punica achieves continuous batching? I didn't find it in this repo. Thanks a lot!

**Comment by abcdabcd987** [comment]
I plan to extract the logic to a seperate file. In the meanwhile, you can refer to the following to examples:

- https://github.com/punica-ai/punica/blob/591b59899f0a20760821785d06b331c8a2e5cb86/benchmarks/bench_textgen_lora.py#L133
- https://github.com/punica-ai/punica/blob/591b59899f0a20760821785d06b331c8a2e5cb86/examples/tui-multi-lora.py#L218
