### ISSUE TITLE
improve bgmv expand kernel performance

### ISSUE THREAD

**Issue by yyccli** [punica-ai/punica#47]
Hi, sorry to bother you again.
I'm using bgmv in our llm serving system since the sgmv kernels not ready. I do some profiling on bgmv kernels and find that the performance of expand kernel is worse compared to shrink kernel.
e.g. let's take batch_size = 4096, hidden_dim=4096 and lora_rank = 8. The performance profiled by ncu is shown below:
<img width="1676" alt="image" src="https://github.com/punica-ai/punica/assets/25741435/eaa0ca03-3fca-4c22-87d8-bd2ba61a2dfe">
It seems that expand kernel's memory throughput is lower than shrink kernel. It's reasonable because all memory operations in expand kernel deal with global memory. 
My question is that why expand kernel doesn't use pipeline asynchronous memory copy from global to shared memory?

**Comment by yyccli** [comment]
After studying your code, i find that the expand kernel indeed can not use pipeline... :cold_sweat:
Is there any way to improve it ...? or maybe just turn to learn your sgmv kernels first
thanks for the code btw

**Comment by chenhongyu2048** [comment]
seems custom sgmv is still not pushed out...
may I know if you have any solution?

**Comment by yyccli** [comment]
> seems custom sgmv is still not pushed out... may I know if you have any solution?

Hi, maybe you can refer to vLLM project, it seems that some community contributors have implemented sgemv operators using triton, you can look for the relevant pr

**Comment by chenhongyu2048** [comment]
> > seems custom sgmv is still not pushed out... may I know if you have any solution?
> 
> Hi, maybe you can refer to vLLM project, it seems that some community contributors have implemented sgemv operators using triton, you can look for the relevant pr

Thanks, I have found the triton sgemv kernel, but it didn't fit my needs.
Anyway, thanks again for your reply.
