### ISSUE TITLE
Rotary_pos_emb Miss?

### ISSUE THREAD

**Issue by chenhongyu2048** [punica-ai/punica#50]
I have a question about the Rotary_pos_emb function in llama. I have not find this function in the code, and I can only guess that it has been implemented in `_kernels.batch_decode(` in the `batch_decode` function?
So if i want to find Rotary_pos_emb, I need to check flashinfer's code?

**Comment by abcdabcd987** [comment]
Correct. Position embedding is within the attention kernel. Punica just calls FlashInfer. https://github.com/punica-ai/punica/blob/591b59899f0a20760821785d06b331c8a2e5cb86/csrc/flashinfer_adapter/flashinfer_all.cu#L96

**Comment by chenhongyu2048** [comment]
Thank you for your prompt answer!
btw, punica is a very rewarding job.

**Comment by abcdabcd987** [comment]
Thanks!
