### ISSUE TITLE
Question about the work

### ISSUE THREAD

**Issue by Gorluxor** [punica-ai/punica#6]
Nice work. Your work focuses on LLM inference and optimizing the inference speed. 
Do you support backprop? 
If not, how difficult would it be to allow backprop to work with the custom Cuda kernel?

**Comment by abcdabcd987** [comment]
Thanks!

Currently we don't support backprop. And backprop would require significant amount of work. And personally speaking, I don't see too much performance gain in finetuning multiple models in one batch.

I recommend using PEFT or other libraries to finetune your model. Then you can use punica to serve all of them. I'm working on a finetuning recipe and also a script to convert PEFT weights to our format. I'll let you know once it's out :)

**Comment by Gorluxor** [comment]
Yeah guess as much from the title alone, but wanted to verify. 
Once again good work, and thanks for the fast reply.
