### ISSUE TITLE
License to use this library?

### ISSUE THREAD

**Issue by Algy** [punica-ai/punica#9]
Do you have any plan to include any OSS license? I'd like to use this in my project, but it should be compatible with the license of this.

**Comment by abcdabcd987** [comment]
Yes. Initially I wanted to use Apache. But I found that [UW](https://comotion.uw.edu/licensing/open-source/) prohibits Apache and recommends BSD. We are evaluating options.

**Comment by Algy** [comment]
Alright. I'll watch this repo so I pick it up as soon as license added. thanks!

**Comment by kir0ul** [comment]
Maybe this issue should be kept open until the license has been picked?

**Comment by abcdabcd987** [comment]
Apache-2.0

https://github.com/punica-ai/punica/commit/7940139530a4f8df9c480599969b454e9ce6f865
